---
name: "Collection code testing"

on: push

jobs:
  # ----------------------------------- #
  # Galaxy Importer
  # ----------------------------------- #
  galaxy_importer:
    name: Test galaxy-importer
    runs-on: ubuntu-20.04 # Older version to be compatible with old python
    env:
      PY_COLORS: 1 # allows molecule colors to be passed to GitHub Actions
      ANSIBLE_FORCE_COLOR: 1 # allows ansible colors to be passed to GitHub Actions
      GALAXY_IMPORTER_CONFIG: galaxy-importer/galaxy-importer.cfg
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11 
      - uses: actions/checkout@v3
      - name: Install requirements
        # Install the specific version of galaxy-importer used on galaxy.ansible.com
        # The old version conflicts with our versions of other tooling,
        # so we let the galaxy-importer version resolve remaining requirements.
        run: |
          pip install "galaxy-importer"
      - name: 'Build ansible package'
        run: ansible-galaxy collection build --force seiko.smartcs
      - name: 'Run galaxy-importer checks'
        run: python -m galaxy_importer.main *.tar.gz
      - uses: actions/upload-artifact@v3
        with:
          name: importer-logs
          path: ./importer_result.json